# Site settings
title: The Southern Gothic Codex
email: contact@thesoutherngothiccodex.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the landing page for the Southern Gothic Codex podcast. We will post our weekly podcast feed
  to this site as well as itunes, libsyn and other auto formats.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thesoutherngothiccodex.com" # the base hostname & protocol for your site
twitter_username: thesnarkyone
github_username:  thesnarkyone

# Build settings
markdown: kramdown
